import authorOne from "../../assets/desktopLibrary/one/Avatar_32.png";
import imageOne from "../../assets/desktopLibrary/one/img_marketing_web_cardimg_marketing_web_card@2x (24).png";

export const mockData = [
  {
    id: 1,
    author: authorOne,
    detailsLink: "#",
    image: imageOne,
    stats: { time: "30:53", distance: "6,248 M" },
    title: "just a couple liners here",
    workouts: { count: 6, link: "" },
  },
  {
    id: 2,
    author: authorOne,
    detailsLink: "#",
    image: imageOne,
    stats: { time: "30:53", distance: "6,248 M" },
    title: "just a couple liners here",
    workouts: { count: 6, link: "" },
  },
  {
    id: 3,
    author: authorOne,
    detailsLink: "#",
    image: imageOne,
    stats: { time: "30:53", distance: "6,248 M" },
    title: "just a couple liners here",
    workouts: { count: 6, link: "" },
  },
  {
    id: 4,
    author: authorOne,
    detailsLink: "#",
    image: imageOne,
    stats: { time: "30:53", distance: "6,248 M" },
    title: "just a couple liners here",
    workouts: { count: 6, link: "" },
  },
  {
    id: 5,
    author: authorOne,
    detailsLink: "#",
    image: imageOne,
    stats: { time: "30:53", distance: "6,248 M" },
    title: "just a couple liners here",
    workouts: { count: 6, link: "" },
  },
  {
    id: 6,
    author: authorOne,
    detailsLink: "#",
    image: imageOne,
    stats: { time: "30:53", distance: "6,248 M" },
    title: "just a couple liners here",
    workouts: { count: 6, link: "" },
  },
  {
    id: 7,
    author: authorOne,
    detailsLink: "#",
    image: imageOne,
    stats: { time: "30:53", distance: "6,248 M" },
    title: "just a couple liners here",
    workouts: { count: 6, link: "" },
  },
  {
    id: 8,
    author: authorOne,
    detailsLink: "#",
    image: imageOne,
    stats: { time: "30:53", distance: "6,248 M" },
    title: "just a couple liners here",
    workouts: { count: 6, link: "" },
  },
];
